### PR TITLE
Way 50 jim

### PR DESCRIPTION
**Pull request by jimbrkr**
The error Jason had with one of my functions should no longer be an issue. I removed it since it may not even be needed with Gregg's. This version should also be using JDK 1.8.

### CODE REVIEW

**Comment by JDSustar** [comment]
/sigh.

I'm now getting a runtime error of:

```
java.sql.SQLException: Invalid column name
    at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.java:3724)
    at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl.java:2799)
    at oracle.jdbc.driver.OracleResultSet.getObject(OracleResultSet.java:462)
    at com.SegmentController.segments(SegmentController.java:56)
    at com.RouteController.generateRoute(RouteController.java:36)
    at com.Application.main(Application.java:16)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

It doesn't like:
`double[] coord = JGeometry.load((oracle.sql.STRUCT) rs.getObject("geom")).getOrdinatesArray();`

**Comment by jimbrkr** [comment]
I wonder....if Oracle is case sensitive. I didn't think it was though..Although looking at the code, I pulled that line from Gregg's code (not blaming you Gregg). But accessing the same column works when "geom" is all caps, ie "GEOM"

edit: accessing that column in LocationController I mean, you get the idea.

**Comment by JDSustar** [comment]
I fixed it. It's good now.

:+1:

**Comment by jimbrkr** [comment]
@JDSustar We okay to close this pull request right?

**Comment by JDSustar** [comment]
Since it's on a branch and not master, I would say just go ahead and do it.

Normally I would prefer if 2 people reviewed it.

**Comment by jimbrkr** [comment]
@JDSustar I also ask that because I thought you already merged WAY50-Jim with WAY-50

**Comment by JDSustar** [comment]
I haven't done any merging.

**Comment by jimbrkr** [comment]
@JDSustar  Nvm, was looking at the wrong branch. I can wait if you'd like to merge. No one seems to like reviewing pull requests though

**Comment by JDSustar** [comment]
Just do it.

**Pull request merged**
