### PR TITLE
Way 55

### PR DESCRIPTION
**Pull request by thomas-forte**
pull request

### CODE REVIEW

**Comment by JDSustar** [comment]
@thomas-forte look good. For some reason, your solution keeps adding duplicate lines to the .idea/libraries files. I'm going to add the .idea/libraries folder to the gitignore file, but I just wanted to let you know why I made a commit to your branch.

:+1:

**Comment by thomas-forte** [comment]
That's fine, It's probably due to the face I go back and forth between windows and mac.

**Comment by thomas-forte** [comment]
I will spam emails till I get another thumbs up, I swear!

**Comment by jimbrkr** [comment]
Works great. Thumbs up!

**Pull request merged**
