### PR TITLE
Way 46

### PR DESCRIPTION
**Pull request by thomas-forte**
Wanting to add utility package to master. The Coordinate class is finished and everyone can use it in their implementations. The Utility class in in progress.

### CODE REVIEW

**Comment by JDSustar** [comment]
I like the way you did it with giving the type in the constructor, but I'm not sure I like your enum names. They aren't really One thing to Another when you load them. They are either one thing or another thing, and the class knows it needs to create the thing that they are _not_. 

When you make that change, I'll thumbs up. (Because I checked... it builds).

**Comment by JDSustar** [comment]
Also, those are awesome comments. Did they autogenerate somehow?

**Comment by thomas-forte** [comment]
I'll change up the enum types to just be NAD27 or GCS. The comments are all me.

**Comment by JDSustar** [comment]
Which ones are which? NAD27 is SPC? and GCS is LatLong?
That's fine.

There's got to be a good way to auto-generate those comments.

EDIT: https://www.jetbrains.com/idea/help/creating-documentation-comments.html

**Comment by thomas-forte** [comment]
yes exactly. gcs == global coordinate system. I'm sure they is, the /*\* auto types the anotations

**Comment by JDSustar** [comment]
@thomas-forte do you think we could merge an earlier (working) version? Or do you think you'll have this fixed by tonight? I just want to get other member's access to these tools.

**Comment by thomas-forte** [comment]
I will try but merge the earlier one for now. What I am doing to fix this issue should not effect anyone else's work.

**Comment by JDSustar** [comment]
Should I merge 7b2510a?

**Comment by thomas-forte** [comment]
I got it to work but it is hacky here is the completed test I ran. The E/N is from the database data, the Lat/Long is what earthpoint gives us, and the jhlabs is the library's value. I copied the "nad" folder into the build folder after compiling to do this. A "clean" build will erase this but I'm not sure how to include the folder into the build.

# 

Name: Stillman Hall
E/N:      1825399.996123 729498.427258
Lat/Long: 40.00176 -83.01079

# jhlabs:   40.00176 -83.01079

Name: Evans Lab
E/N:      1825298.894970 729843.911312
Lat/Long: 40.00271 -83.01116

# jhlabs:   40.00271 -83.01116

Name: Smith Lab
E/N:      1824759.234672 729830.663313
Lat/Long: 40.00266 -83.01309

# jhlabs:   40.00266 -83.01309

Name: Dreese Lab
E/N:      1823961.272278 729648.987293
Lat/Long: 40.00215 -83.01593

# jhlabs:   40.00215 -83.01593

Name: Prior Lib
E/N:      1823568.197467 726938.919614
Lat/Long: 39.99470 -83.01728
jhlabs:   39.99470 -83.01727

sorry about the strange formatting markup is sometimes a pain.

**Comment by JDSustar** [comment]
I've changed one small thing to remain consistent in where the main method is. So other auto-generated stuff I committed too.

I deleted my build folder and did a clean build and run. The conversion worked great.

Nice job, Tommy. :+1:

**Comment by jimbrkr** [comment]
The code builds successfully, but when I try and run it I get these errors:

Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.Application.main(Application.java:13)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.NullPointerException
    at java.io.Reader.<init>(Reader.java:78)
    at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
    at jhlabs.map.proj.ProjectionFactory.readProjectionFile(ProjectionFactory.java:396)
    at jhlabs.map.proj.ProjectionFactory.getNamedPROJ4CoordinateSystem(ProjectionFactory.java:469)
    at utilities.Utility.<clinit>(Utility.java:15)
    ... 6 more

**Comment by JDSustar** [comment]
Jim, you're sure you have the latest on this branch? This is the exact issue Tommy was trying to fix.

**Comment by jimbrkr** [comment]
@JDSustar, I have deleted my local branch twice now to make sure there wasn't an issue there and checked out WAY-46 as a local branch to build and test. Every time I have gotten those errors

**Comment by thomas-forte** [comment]
@jimbrkr after building check to see that the file "build/resources/main/nad27" exists. NOTE: the solution I made only works with inteliJ, it will break with other IDE's

**Comment by JDSustar** [comment]
He's used Android Studio, so I would assume the fix would work (it being an IntelliJ product)

**Comment by JDSustar** [comment]
So apparently my commit removed some stuff from the IML file. Could you pull and try again, @jimbrkr ?

**Comment by jimbrkr** [comment]
I'm getting these errors now..

Error:(3, 46) java: package org.springframework.boot.autoconfigure does not exist
Error:(4, 32) java: package org.springframework.boot does not exist
C:\Users\Jim\Documents\GitHub\wayfinding-osu-capstone-api\src\main\java\com\Application.java
Error:(5, 46) java: package org.springframework.context.annotation does not exist
Error:(8, 2) java: cannot find symbol
  symbol: class ComponentScan
Error:(9, 2) java: cannot find symbol
  symbol: class EnableAutoConfiguration
C:\Users\Jim\Documents\GitHub\wayfinding-osu-capstone-api\src\main\java\com\LocationController.java
Error:(4, 47) java: package org.springframework.web.bind.annotation does not exist
Error:(5, 47) java: package org.springframework.web.bind.annotation does not exist
Error:(12, 6) java: cannot find symbol
  symbol:   class RequestMapping
  location: class com.LocationController
Error:(10, 2) java: cannot find symbol
  symbol: class RestController

**Comment by JDSustar** [comment]
Those are Gradle.Build errors. Make sure you sync your gradle files.

http://stackoverflow.com/questions/19932793/syncing-android-studio-project-with-gradle-files

**Comment by jimbrkr** [comment]
Okay, now I'm back to getting the errors I had the first time I commented.

**Comment by thomas-forte** [comment]
I am using Jason's current commit in inteliJ, It is working as expected. Perhaps Andriod Studios build paths are different or the configs are different.

**Comment by JDSustar** [comment]
@jimbrkr any luck with IntelliJ?

**Comment by jimbrkr** [comment]
@JDSustar Just got back from staff meeting. But I loaded it up in IntelliJ and got the same problem Tommy was having in class with the gradle build. Know how he fixed that, @thomas-forte?

**Comment by jimbrkr** [comment]
After a rebuild, Tommy's code worked great in IntelliJ. A simple rebuild fixed the gradle build error. Sadly, seems like we are all going to need to use IntelliJ over Android Studio because of the build folder issue. 

So finally, I am upvoting this. Merge away!

:+1:

**Pull request merged**
