### PR TITLE
Way 29

### PR DESCRIPTION
**Pull request by greggdent**
Route generated based on current location.

### CODE REVIEW

**Comment by JDSustar** [comment]
Is it possible to change the Coordinate .distance stuff back to feet so we don't have these crazy decimals?

Or perhaps two functions? .distanceInFeet and .distanceInGCS?

**Comment by JDSustar** [comment]
Other than the above comment, I've seen this code and tested it. :+1:

**Comment by greggdent** [comment]
At the time, the distance formula in feet wasn't working for me, but then later I remember Tommy saying something about not adding the conversion function before returning the value. Haven't thought much about it since.

**Comment by JDSustar** [comment]
@thomas-forte Can you weigh in on this? Think we could change it back?

**Comment by greggdent** [comment]
My guess is the missing conversion function was the problem. I just didn't catch it and moved on. I can test this tomorrow. No need for Tommy to do anything

**Comment by thomas-forte** [comment]
Can we get this pulled? So we can update the server.

**Comment by JDSustar** [comment]
Yes. I can't from my phone. Just do it.

**Pull request merged**
