### PR TITLE
Route Calculator

### PR DESCRIPTION
**Pull request by JDSustar**
A lot of changes to review.

These are the culmination of Jim's, Gregg's, and my work, although the pull request was easier if I just manually merged our changes on to one branch and then merged that to master.

Really, I would recommend viewing the files without the diffs if you really want to code review them. It might make it easier to see since there are so many changes.

You want to focus your attention on
- Application
- Location
- LocationCollection
- LocationController
- Node
- Route
- RouteController
- Segment
- SegmentCollection
- SegmentController

I would really like a thumbs up from every person on this one since it is central to our system.

### CODE REVIEW

**Comment by greggdent** [comment]
I couldn't find any problems :+1:

**Comment by jimbrkr** [comment]
I am able to build with no errors, however when I try and run the application, it fails to bind to the server correctly. Says that the server address is already in use. Is multiple people trying to access the server at the same time going to be an issue?

**Comment by thomas-forte** [comment]
I too could build and run this without errors. I did some test calls but could not figure out the syntax for generateRoute

**Comment by JDSustar** [comment]
@jimbrkr I assume your error was something like:

`java.net.BindException: Address already in use: bind`

If so, that means port 9000 is already being used by something on your computer and the API server cannot be started because the port is already bound to something else. Try each of the following fix this:
- Open your task manager (or whatever it is on Mac) and end any running Java Programs
- Restart IntelliJ
- Restart your computer

If all of these don't work, we can take a closer look.

**Comment by JDSustar** [comment]
@thomas-forte I should have included that in the initial description.

You can call the method in 2 ways: you can simply call .generateRoute(int, int) on an instance of the RouteController or you can start the Spring API Server and go to `localhost:9000/generateRoute?from=10564&to=10570`

Let me know if you have problems with those.

**Comment by jimbrkr** [comment]
All good. It wouldn't let me break it :( 

:+1:

**Pull request merged**
