### PR TITLE
Way 50 gregg

### PR DESCRIPTION
**Pull request by greggdent**
Jim and I's most updated, merged, executable code

### CODE REVIEW

**Comment by JDSustar** [comment]
What's with all the commented out stuff? Can that be deleted?

**Comment by greggdent** [comment]
It's just some code I tested with that didn't exactly work. I realize now that I worked on it after I created a new pull request, then committed.

**Comment by JDSustar** [comment]
:+1:

**Comment by jimbrkr** [comment]
:+1:

**Pull request merged**
